language: python
cache: pip
sudo: false
python:
  - "3.6"
services:
  - xvfb  # Allows for tests that require the GUI to run
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install mypy
  - pip install pytest_mock
script:
  - mypy kintercrypt tests --config-file=tox.ini  # Type checking
  - pytest --cov=kintercrypt/ --cov-report term-missing
after_success:
  - coveralls
