language: python
sudo: false
python:
  - "3.6"
services:
  - xvfb
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest --cov=kintercrypt/ --cov-report term-missing
after_success:
  - coveralls
